
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWs", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWs {


    /**
     * 
     * @return
     *     returns java.util.List<service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service/", className = "service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service/", className = "service.GetComptesResponse")
    @Action(input = "http://service/BanqueWs/getComptesRequest", output = "http://service/BanqueWs/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcompte", targetNamespace = "http://service/", className = "service.Getcompte")
    @ResponseWrapper(localName = "getcompteResponse", targetNamespace = "http://service/", className = "service.GetcompteResponse")
    @Action(input = "http://service/BanqueWs/getcompteRequest", output = "http://service/BanqueWs/getcompteResponse")
    public Compte getcompte(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param monatant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDh", targetNamespace = "http://service/", className = "service.ConversionEuroToDh")
    @ResponseWrapper(localName = "ConversionEuroToDhResponse", targetNamespace = "http://service/", className = "service.ConversionEuroToDhResponse")
    @Action(input = "http://service/BanqueWs/ConversionEuroToDhRequest", output = "http://service/BanqueWs/ConversionEuroToDhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "monatant", targetNamespace = "")
        double monatant);

}
